### ISSUE TITLE
Cannot add a new or edit a repository with new UI.

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#21] opened 2015-12-28 17:13 UTC
When trying to add a new repository entry under 'Updates' tab, after fill the 'Identifier', 'Name' and 'URL' fields, the 'Add' button is enabled but nothing happens when clicking on it. 

![screenshot from 2015-12-28 15-03-25](https://cloud.githubusercontent.com/assets/699330/12022190/aeb580e4-ad74-11e5-9763-98b6a4336305.png)

The same happens after edit any field of an existent repository - nothing happens after click on Save button. In addition, to both actions, nothing happens on backend side. This happens on Fedora 23 host machine.

**Comment by danielhb** [comment] 2015-12-29 18:50
I'll close this issue because it's a replicate of #11 

Thanks!

**Comment by pvital** [comment] 2016-01-11 10:47
@danielhb the problem reported in this issue is different from issue #11.
Here, the button the to add or edit the fields of an repository is not working. I request you to re-open it.

**Comment by alinefm** [comment] 2016-07-06 14:46
Hi @danielhb! Hi @pvital!

I have confirmed those problems on 188db297608671d39b8b5bbdee23caf04cc1d620
But for the edit operation, no dialog is displayed to collect user inputs.
No errors on Firebug too.

**Comment by alinefm** [comment] 2016-07-06 17:02
Please, refer to #113 to the edit issue.

**Comment by pvital** [comment] 2016-07-07 13:02
@alinefm I can confirm on released 2.2.0 and 188db29. Also could confirm #113 and updated the issue.

**Closed as completed** 2016-08-05 15:08 UTC
Labels: bug, UI
