### ISSUE TITLE
scss compilation fails with latest upstream code from tarball

### ISSUE THREAD

**Issue by potula-chandra** [kimchi-project/gingerbase#51] opened 2016-03-18 08:25 UTC
[root@localhost gingerbase]# make -C ui/css css
make: Entering directory '/home/chandra/wok/src/wok/plugins/gingerbase/ui/css'
echo "Compiling .scss file src/gingerbase.scss"
Compiling .scss file src/gingerbase.scss
sassc -s expanded src/gingerbase.scss gingerbase.css
sassc: error: Error: "#host-info-container .basic-information-list" failed to @extend ".row".
       The selector ".row" was not found.
       Use "@extend .row !optional" if the extend should be able to fail.
        on line 188 of src/modules/_host.scss

> > ```
> >     @extend .row; // Extending bootstrap .row clearfix util
> > ```
> > 
> >    --------^

Makefile:515: recipe for target 'css' failed
make: **\* [css] Error 1
make: Leaving directory '/home/chandra/wok/src/wok/plugins/gingerbase/ui/css'

**Comment by frediz** [comment] 2016-04-12 13:08
I have the same error in released version 2.1.0.
Anyone can help on that ?
Thanks

**Comment by alinefm** [comment] 2016-04-13 18:16
Hi @chandrureddy ! Hi @frediz !

Which OS are you using? I've just tried on Fedora 23 and it worked without issues.

[alinefm@alinefm-TP440 gingerbase]$ sudo make -C ui/css css
make: Entering directory '/home/alinefm/wok/src/wok/plugins/gingerbase/ui/css'
echo "Compiling .scss file src/gingerbase.scss"
Compiling .scss file src/gingerbase.scss
sassc -s expanded src/gingerbase.scss gingerbase.css
make: Leaving directory '/home/alinefm/wok/src/wok/plugins/gingerbase/ui/css'

Do you have all the UI development dependencies installed?

$ sudo yum install gcc-c++ python-devel python-pip
$ sudo pip install cython libsass

**Comment by frediz** [comment] 2016-04-15 08:29
Hi @alinefm ,
I'm doing the compilation with libsass-python on Debian (i.e. the python sass compiler). Btw it used to work in 2.0.0 but it was an earlier version of libsass-python which failed on ppc64el. 0.11.0 works on all Debian architectures.

```
ii  libsass0:amd64                   3.3.4-1                      amd64        C/C++ port of the Sass CSS precompiler
ii  pysassc                          0.11.0-2                     all          SASS for Python: command line utility for libsass
ii  python-libsass                   0.11.0-2                     amd64        SASS for Python: a straightforward binding of libsass for Python
ii  python3-libsass                  0.11.0-2                     amd64        SASS for Python 3: a straightforward binding of libsass for Python
```

**Comment by samhenri** [comment] 2016-04-20 18:05
Have you updated wok? Can you confirm if your gingerbase.scss looks like this?

https://github.com/kimchi-project/gingerbase/blob/167b7b162394185dfd20e38907d5889838de9c5b/ui/css/src/gingerbase.scss

**Comment by samhenri** [comment] 2016-04-20 18:06
These `@import` calls should had fixed this problem:

```
// Bootstrap mixins
@import "../../../../../../../ui/css/src/vendor/bootstrap-sass/bootstrap/mixins";

// Bootstrap classes
@import "../../../../../../../ui/css/src/vendor/bootstrap-sass/bootstrap/grid";
```

Check if your Wok project path is correct and if these `/vendor/` files are there. Just to make sure, check user access roles. Since these folders only have SCSS files I think it is ok to grant 0777 user access to them.

**Comment by frediz** [comment] 2016-04-22 08:50
@samhenri you did it :)
The latest gingerbase.scss from git doesn't work, as it needs wok to have _compact.scss which is not in the 2.1.0 tarball.
But the 2 imports "mixins" and "grid" in your latest comment did it, it now compiles.
Sorry to bother about that, but I think it's important that the whole kimchi project compiles and run mostly properly from released tarballs, especially for distro integration. Thanks for helping!

Also not sure about that, but last line of the file does not have a ";" : 

```
@import "modules/line-chart"
```

**Comment by samhenri** [comment] 2016-04-25 11:24
I didn't knew that it was possible to use wok tarball to develop Wok plugins, I thought that the SCSS files were not included due to Fedora and other distro policies. @alinefm @danielhb any comments?

Regarding the import line, as in CSS the last property does not require a semicolon. If you add other lines below it then you would have to.

**Comment by alinefm** [comment] 2016-07-06 16:58
Hi @chandrureddy! Hi @frediz!

I could not reproduce that on 188db297608671d39b8b5bbdee23caf04cc1d620

When I tried to build gingerbase out of the wok structure I got the following error:

```
[alinefm@alinefm-TP440 gingerbase-master]$ sudo make -C ui/css css
make: Entering directory '/home/alinefm/Downloads/gingerbase-master/ui/css'
echo "Compiling .scss file src/gingerbase.scss"
Compiling .scss file src/gingerbase.scss
sassc -s expanded src/gingerbase.scss gingerbase.css
sassc: error: Error: File to import not found or unreadable: ../../../../../../../ui/css/src/modules/wok-variables
       Parent style sheet: /home/alinefm/Downloads/gingerbase-master/ui/css/src/gingerbase.scss
        on line 22 of src/gingerbase.scss
>> @import "../../../../../../../ui/css/src/modules/wok-variables";
   ^

Makefile:515: recipe for target 'css' failed
make: *** [css] Error 1
make: Leaving directory '/home/alinefm/Downloads/gingerbase-master/ui/css'
```

But after moving the gingerbase code under src/wok/plugins I could compile the CSS without issues:

```
[alinefm@alinefm-TP440 gingerbase-master]$ sudo make -C ui/css css
make: Entering directory '/home/alinefm/wok/src/wok/plugins/gingerbase-master/ui/css'
echo "Compiling .scss file src/gingerbase.scss"
Compiling .scss file src/gingerbase.scss
sassc -s expanded src/gingerbase.scss gingerbase.css
make: Leaving directory '/home/alinefm/wok/src/wok/plugins/gingerbase-master/ui/css'
```

Could you confirm that and provide your results here? Otherwise, I think we can close this issue.

**Comment by alinefm** [comment] 2016-10-21 17:56
Closing based on last comment. Please reopen if the problem persists to you.

**Closed as completed by alinefm** 2016-10-21 17:56 UTC
