### ISSUE TITLE
Cannot update system on Ubuntu 15.10

### ISSUE THREAD

**Issue by pvital** [kimchi-project/gingerbase#26] opened 2015-12-29 18:41 UTC
After get the list of available packages to update on a Ubuntu 15.10 host machine, and clicked on "Update All" button, the "Update Progress" box shows up but nothing happens.

![screenshot from 2015-12-29 16-28-26](https://cloud.githubusercontent.com/assets/699330/12039777/7866cad0-ae4a-11e5-89ec-dfe2327a083b.png)

Looking at the REST response in Firebug console, the return of the POST command was: 

```
{
  "reason":"GGBPKGUPD0003E: Error while getting packages marked to be updated. Details: E:Not locked"
,
  "code":"500 Internal Server Error"
} 
```

The same happens when using REST command by console:

```
$  curl -k -u test -H "Content-Type: application/json" -H "Accept: application/json" 'https://192.168.122.155:8001/plugins/gingerbase/host/swupdate' -X POST -d'{}'
Enter host password for user 'test':
{
  "reason":"GGBPKGUPD0003E: Error while getting packages marked to be updated. Details: E:Not locked",
  "code":"500 Internal Server Error"
} 
```

**Comment by danielhb** [comment] 2015-12-29 18:45
Please check out #20 and have a word with @jrziviani 

It seems the issues might be related with each other

**Comment by pvital** [comment] 2015-12-29 18:54
@danielhb This is a different issue. #20 happens on Fedora 23 with me (I start an update and can see the progress on its box but if I change to a different tab and move back to Update tab I can not see the progress).

Here, in this issue, the progress cannot start.

**Comment by danielhb** [comment] 2015-12-29 18:59
Well, #20 is being fixed by @jrziviani as we speak. And it includes an UI fix too that's independent of distro.

Perhaps we might want to wait and see how far the fix for #20 can go to help solving this one.

**Comment by jrziviani** [comment] 2015-12-29 19:55
Yes, I just got this one while testing the progress window with Ubuntu. The problem is within:

``` python
    with self.pkg_lock():
        apt_cache.update()
        apt_cache.upgrade()
```

I don't know why this code was written like this but **AFAIK** we shouldn't use this lock because apt_cache.{update, upgrade} knows how to handle it by themselves. Look, for example, the code of apt_cache.update():

``` python
/usr/lib/python2.7/dist-packages/apt/cache.py
def update(self, fetch_progress=None, pulse_interval=0, raise_on_error=True, sources_list=None):                                                            
(snip)                                                                                                    
¦   lockfile = apt_pkg.config.find_dir("Dir::State::Lists") + "lock"                                           
¦   lock = apt_pkg.get_lock(lockfile) 
¦   if lock < 0:                                                                                               
¦   ¦   raise LockFailedException("Failed to lock %s" % lockfile) 
```

As per https://apt.alioth.debian.org/python-apt-doc/library/apt_pkg.html:

> apt_pkg.get_lock(filename: str, errors=False) → int
> Create an empty file at the path specified by the parameter filename and lock it. If this fails and errors  is True, the function raises an error. If errors is False, the function returns -1.
> The lock can be acquired multiple times within the same process, and can be released by calling os.close() on the return value which is the file descriptor of the created file.

I went a little bit further to understand how these both get_lock() and with pkg_lock: are implemented, and this is the guy (**read the comment**):

``` c++
// GetLock - Gets a lock file                       /*{{{*/
// ---------------------------------------------------------------------
/* This will create an empty file of the given name and lock it. Once this
    is done all other calls to GetLock in any other process will fail with
    -1. The return result is the fd of the file, the call should call
    close at some time. */
int GetLock(string File,bool Errors)
```

So we are basically trying to lock the same file twice. I'm working on it.

**Comment by danielhb** [comment] 2015-12-31 10:24
A fix was pushed upstream. Please check if this issue is fixed.

**Comment by pvital** [comment] 2015-12-31 12:55
Fixed

**Comment by danielhb** [comment] 2015-12-31 12:57
Thx

**Closed as completed by danielhb** 2015-12-31 12:57 UTC
Labels: bug, UI, backend
